### ISSUE TITLE
Static build

### ISSUE THREAD

**Issue by ghost** [cygwinports/mingw64-x86_64-libxml2#1]
Currently only shared library is built:

~~~
usr/x86_64-w64-mingw32/sys-root/mingw/bin/libxml2-2.dll
usr/x86_64-w64-mingw32/sys-root/mingw/lib/libxml2.dll.a
~~~

Workaround; static library is available here:

http://repo.msys2.org/mingw/x86_64

**Comment by cup** [comment]
https://github.com/cygwinports/mingw64-x86_64-libxml2/issues/1
https://github.com/libvips/libvips/issues/1271
https://github.com/libvips/libvips/issues/365

**Comment by yselkowitz** [comment]
Please refrain from using issue trackers for feature requests.

**Comment by ghost** [comment]
It's bug not feature
